### ISSUE TITLE
babel-loader should be pinned

### ISSUE THREAD

**Issue by OmgImAlexis** [euvl/vue-js-modal#324]
`babel-loader` is currently setup to use `latest` it should be using version `7` as the latest needs changes before it'll work. Simply replacing latest with `7` fixes the issue.

```
ERROR in ./src/index.js
Module build failed: Error: Cannot find module '@babel/core'
 babel-loader@8 requires Babel 7.x (the package '@babel/core'). If you'd like to use Babel 6.x ('babel-core'), you should install 'babel-loader@7'.
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:581:15)
    at Function.Module._load (internal/modules/cjs/loader.js:507:25)
    at Module.require (internal/modules/cjs/loader.js:637:17)
    at require (internal/modules/cjs/helpers.js:20:18)
    at Object.<anonymous> (/Users/xo/code/vue-js-modal/node_modules/babel-loader/lib/index.js:8:11)
    at Module._compile (internal/modules/cjs/loader.js:689:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:700:10)
    at Module.load (internal/modules/cjs/loader.js:599:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:538:12)
    at Function.Module._load (internal/modules/cjs/loader.js:530:3)
    at Module.require (internal/modules/cjs/loader.js:637:17)
    at require (internal/modules/cjs/helpers.js:20:18)
    at loadLoader (/Users/xo/code/vue-js-modal/node_modules/loader-runner/lib/loadLoader.js:13:17)
    at iteratePitchingLoaders (/Users/xo/code/vue-js-modal/node_modules/loader-runner/lib/LoaderRunner.js:169:2)
    at runLoaders (/Users/xo/code/vue-js-modal/node_modules/loader-runner/lib/LoaderRunner.js:362:2)
    at NormalModule.doBuild (/Users/xo/code/vue-js-modal/node_modules/webpack/lib/NormalModule.js:179:3)
    at NormalModule.build (/Users/xo/code/vue-js-modal/node_modules/webpack/lib/NormalModule.js:268:15)
    at Compilation.buildModule (/Users/xo/code/vue-js-modal/node_modules/webpack/lib/Compilation.js:146:10)
    at moduleFactory.create (/Users/xo/code/vue-js-modal/node_modules/webpack/lib/Compilation.js:433:9)
    at factory (/Users/xo/code/vue-js-modal/node_modules/webpack/lib/NormalModuleFactory.js:253:5)
    at applyPluginsAsyncWaterfall (/Users/xo/code/vue-js-modal/node_modules/webpack/lib/NormalModuleFactory.js:99:14)
    at /Users/xo/code/vue-js-modal/node_modules/tapable/lib/Tapable.js:268:11
    at NormalModuleFactory.params.normalModuleFactory.plugin (/Users/xo/code/vue-js-modal/node_modules/webpack/lib/CompatibilityPlugin.js:52:5)
    at NormalModuleFactory.applyPluginsAsyncWaterfall (/Users/xo/code/vue-js-modal/node_modules/tapable/lib/Tapable.js:272:13)
    at resolver (/Users/xo/code/vue-js-modal/node_modules/webpack/lib/NormalModuleFactory.js:74:11)
    at process.nextTick (/Users/xo/code/vue-js-modal/node_modules/webpack/lib/NormalModuleFactory.js:205:8)
    at process._tickCallback (internal/process/next_tick.js:61:11)
```

**Comment by OmgImAlexis** [comment]
Still an issue.

**Comment by euvl** [comment]
Thanks, will do

**Comment by euvl** [comment]
Actually we are not using @babel/core which is a separate version to  "babel-core" so i think it should be fine.
