### ISSUE TITLE
SSR: Changing the file and then refreshing causes an error.

### ISSUE THREAD

**Issue by seekcx** [euvl/vue-js-modal#37]
Hey, @euvl 

Thank you very much for provide SSR support for this great library.

I encountered a problem in the use, if I nuxt dev mode to change the file, trigger nuxt re-compile, then the page is normal. But if you refresh the page, you will get a mistake:
```log
Nuxt.js Error:

TypeError: Cannot redefine property: $modal
    at Function.defineProperty (native)
    at Object.install (~/.1.2.0@vue-js-modal/dist/ssr.index.js:1:953)
    at Function.Vue.use (/Users/abel/Desktop/test/vue-js-modal/demo/server_side_rendering/node_modules/.2.3.4@vue/dist/vue.runtime.common.js:4114:22)
    at Object.module.exports.Object.defineProperty.value (plugins/vue-js-modal.js:4:4)
    at __webpack_require__ (webpack:/webpack/bootstrap 5eeb6eab07fc43310607:25:0)
    at Object.module.exports.__webpack_exports__.a (.nuxt/index.js:25:14)
    at __webpack_require__ (webpack:/webpack/bootstrap 5eeb6eab07fc43310607:25:0)
    at Object.module.exports.Object.defineProperty.value (server-bundle.js:1545:65)
    at __webpack_require__ (webpack:/webpack/bootstrap 5eeb6eab07fc43310607:25:0)
    at server-bundle.js:95:18
    at Object.<anonymous> (server-bundle.js:98:10)
    at evaluateModule (/Users/abel/Desktop/test/vue-js-modal/demo/server_side_rendering/node_modules/.2.3.4@vue-server-renderer/build.js:5820:21)
    at /Users/abel/Desktop/test/vue-js-modal/demo/server_side_rendering/node_modules/.2.3.4@vue-server-renderer/build.js:5878:18
    at /Users/abel/Desktop/test/vue-js-modal/demo/server_side_rendering/node_modules/.2.3.4@vue-server-renderer/build.js:5870:14
    at Nuxt.renderToString (/Users/abel/Desktop/test/vue-js-modal/demo/server_side_rendering/node_modules/.2.3.4@vue-server-renderer/build.js:6022:9)
    at P (/Users/abel/Desktop/test/vue-js-modal/demo/server_side_rendering/node_modules/.3.0.0@pify/index.js:49:6)
```

I tried the demo you provided, the same as the problem.

**Comment by euvl** [comment]
Hey @seekcx 

Thanks a lot for kind words and using the plugin! 😄 
I am new to nuxt so could you please provide an instruction how i can replicate the bug? 

What I am trying to do: 

1. `cd demo/server_side_rendering`
2. `npm install`
3. `nuxt start`
4. Clicking "Open modal" button
5.  Refreshing the page

And I should get this error, am i right? 
Also which versions of nuxt and vue-js-modal are you using? 

Thanks 😄

**Comment by seekcx** [comment]
Yes,

1. cd demo/server_side_rendering
2. npm install
3. nuxt start
4. Clicking "Open modal" button
5. In the `page/index.vue` make a little change, trigger nuxt re-build
6. Refreshing the page

**Comment by euvl** [comment]
Great, ty. Managed to replicate it 👍

**Comment by euvl** [comment]
Hopefully I have fixed it in `vue-js-modal@1.2.1` 🙏

**Comment by seekcx** [comment]
Well, this issue seems to be resolved, and now it is great.

**Comment by euvl** [comment]
Great! Thanks a lot for your help 👍
